### ISSUE TITLE
organize your data in a dict

### ISSUE THREAD

**Issue by WK-GiHu** [gman2682/school-project#1]
@gman2682 notify me with @WK-GiHu

---

- [x] Read [The Python Tutorial - 5.5. Dictionaries](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)
- [x] Rewrite your data for the States accordingly
  Hint: `key: value`pairs become `State: Tax`
- [x] Update [PayrollCalculator.py](https://github.com/gman2682/school-project/blob/master/PayrollCalculator.py), so i can review
- [x] Read [looping-techniques](https://docs.python.org/3/tutorial/datastructures.html#looping-techniques), how to loop and access data in a `dict`.

**Comment by WK-GiHu** [comment]
@gman2682 

Your `dict` looks ok, but you have choosen the Short `key`, e.g. `AL`. and your States have `Alabama`.

Do you need the Short one?
 - [ ] Yes, i need it later on
 - [ ] No, i simple copy from my previous table.

**Comment by gman2682** [comment]
I adjusted all short ones to actual State names like `Alabama` and `Arizona`

**Comment by WK-GiHu** [comment]
@gman2682 

https://github.com/gman2682/school-project/blob/4841bf64757e5e9396e522afaab5fbe1e61bbdb1/PayrollCalculator.py#L18
- That's, **wrong**, enable this line 18, by removing the `#`, and see the error message.
- This throws a `Unknown: "i"` error.
- Where did you get `i` from?
- Why have you choosen to use `i` at all?

You have checked this, but it seems you didn't read or didn't get it?
   >- [x] Read [The Python Tutorial - 5.5. Dictionaries](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)

Read it again, follow the example how to get the Telephone number from `'jack'`.
**Edit line 18 accordingly**.
