### ISSUE TITLE
us only one `def calculate(opt):` for ALL states

### ISSUE THREAD

**Issue by WK-GiHu** [gman2682/school-project#2]
@gman2682 

- [x] Read about [Don't_repeat_yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

Template:
```
def calculate():
    state = opt.get()
    tax = <get value for state from TAX dict>
    salary = <your tax formula>
    result.set(salary)
```
- [x] Edit the placeholder `<...>` with valid Python syntax
- [x] Update [PayrollCalculator.py](https://github.com/gman2682/school-project/blob/master/PayrollCalculator.py), so i can review

**Comment by gman2682** [comment]
@WK-GiHu Tried my best from what you've given me and what I understood. Please review and give me feedback, thanks! Not a very experienced programmer by the way, (You can probably/obviously tell) so sorry if it takes longer than expected..

**Comment by WK-GiHu** [comment]
@gman2682 

https://github.com/gman2682/school-project/blob/a0547986bc05ec97d71aacacd979041ccccebf82/PayrollCalculator.py#L51

https://github.com/gman2682/school-project/blob/a0547986bc05ec97d71aacacd979041ccccebf82/PayrollCalculator.py#L52
- [ ] To see, what you get, insert the following after line 52:
    ```
    print('state == {}'.format(state))
    ```

----

https://github.com/gman2682/school-project/blob/a0547986bc05ec97d71aacacd979041ccccebf82/PayrollCalculator.py#L53
- [ ]  You didn't fullfil: ***`<get value for state from TAX dict>`***
  Disable this line, for now, with prepending `# `

https://github.com/gman2682/school-project/blob/a0547986bc05ec97d71aacacd979041ccccebf82/PayrollCalculator.py#L54
- [ ]  Yes, but not working yet and could be improved.
  Disable this line, for now, with prepending `# `

https://github.com/gman2682/school-project/blob/a0547986bc05ec97d71aacacd979041ccccebf82/PayrollCalculator.py#L55
This will fail:
 1. You haven't defined a `result = tk.Label(...` in your `__main__` GUI section.
  - [ ] Copy **one** from: https://github.com/gman2682/school-project/blob/a0547986bc05ec97d71aacacd979041ccccebf82/PayrollCalculator.py#L28 to your `__main__` GUI section.
 https://github.com/gman2682/school-project/blob/a0547986bc05ec97d71aacacd979041ccccebf82/PayrollCalculator.py#L55
 2. As it stands, it will work **one time**, because you overwrite your `tk.Label` object with the result of `.get()`.
 - [ ] Rethink this statement, the goal is to update the `tk.Label` with the formula result.
  Disable this line, for now, with prepending `# `

---

Connect it with your `button ... 'Calculate', command=`, on click you should see in your console, e.g:
```
state == Alabama
```
See, my comment in [Issue 1](https://github.com/gman2682/school-project/issues/1) about the `dict`.

**Comment by gman2682** [comment]
Okay, I've followed all instructions and have checked off all of what I have done. I will update the file for your review, thank you. This is a huge help for my school project

**Comment by WK-GiHu** [comment]
@gman2682 

Did you get the expected ouput in your console?
- [ ] Yes, I get ...
 **This answers your inital question**:
  >Need OptionMenu to detect which state is chosen

  How do you want to continue ...
- [ ] No, I get nothing

---

You have checked the following, but I see **no edit**: 
https://github.com/gman2682/school-project/blob/137a3ceaead2798e7d568c58256db1d6c0c7d7a4/PayrollCalculator.py#L56
> 2. As it stands, it will work **one time**, because you overwrite your `tk.Label` object with the result >of `.set()`.
 >- [x] Rethink this statement, the goal is to update the `tk.Label` with the formula result.

Continue with Issue: [`results = tk.Label(...`]()
