### ISSUE TITLE
results = tk.Label(...

### ISSUE THREAD

**Issue by WK-GiHu** [gman2682/school-project#3]
@gman2682 

https://github.com/gman2682/school-project/blob/137a3ceaead2798e7d568c58256db1d6c0c7d7a4/PayrollCalculator.py#L57

OK, but it will fail, because at startup `salary` is unknown.
Read [How to associate a Tkinter variable with a label.](http://effbot.org/tkinterbook/label.htm)

- [x] Change the definition of `result = tk.Label(...` accordingly

**Comment by gman2682** [comment]
I'm not quite getting what your saying as salary would be defined if the formula was finished and it came out as a float? I haven' t defined tax yet (certain tax for each state) which is what I want to do next. File is updated for review.

**Comment by WK-GiHu** [comment]
@gman2682 

> salary would be defined if the formula was finished and it came out as a float?
 Yes, thats correct.
But you can't access `salary`  at startup.
At startup:
- You have not choosen any from the `OptionMenu`
- You have not yet clicked the Button `Calculate`.

Tell, what solution can you imagin?

---

>I haven' t defined tax yet (certain tax for each state) 

You have, it's your `states_dict`, see https://github.com/gman2682/school-project/issues/1

**Comment by WK-GiHu** [comment]
@gman2682 

https://github.com/gman2682/school-project/blob/9a8f4c2ecd4d5e86a2d85372192a1cac18359417/PayrollCalculator.py#L32

You have moved this statement inside `def calculate(...`, thats **wrong**.
***I stated it was OK before, move it back!***
Let it disabeld for now `# `

- Your `result = tk.Label(...` have to be in the `__main__` section and have to be defined at startup - **you have done this**

**Comment by WK-GiHu** [comment]
@gman2682 

You have checked
>- [x] Change the definition of `result = tk.Label(...` accordingly

But you have not changed the definition, the definition begins after `(`.
You have rename the reference variable from `result` to `resultsShown`. 
This does not improve anything, as the value of `resultsShown` is `None` an are not needed further on.

---

>salary is already in the function and can't be used outside of it?

Yes, variable in a function considered `local`.

But even if you can access it, this wouldn't help.
- Vou have to `.set(...)` the calculated `salary` after click of `Button(..., 'Calculate'` and not at startup of the program. 
- Therefore, it is to early in your codeflow. 
- At startup the value of the `tk.Label(... "Total Pay:"` does not exists.

**Comment by WK-GiHu** [comment]
@gman2682 

>I don't quite understand #3 though.

---

1. Variable in a function considered `local`.
   - [ ] Yes, got it 
   - [ ] No, didn't get it

---

2. You have to `.set(...)` the calculated `salary` after click of `Button(..., 'Calculate'` 
and not at startup of the program. 
   - [ ] Yes, got it 
   - [ ] No, didn't get it

3. Therefore, it is to early in your codeflow. 
   - [ ] Yes, got it 
   - [ ] No, didn't get it

---

4. At startup the value of the `tk.Label(... "Total Pay:"` does not exists.
   - [ ] Yes, got it 
   - [ ] No, didn't get it

**Comment by WK-GiHu** [comment]
@gman2682 

### You didn't check anything from the above?
See also: https://github.com/gman2682/school-project/issues/8#issuecomment-546239019

---

>Code is updated

https://github.com/gman2682/school-project/blob/6b7efe24ec6acc17f74eedbc5fe39d33a4f1ff58/PayrollCalculator.py#L55

The Line 55 has **4 Errors**:
- Redefine of a allready defined variable name, here `results` by writing `results = tk.Label(...`.
  This lead to `AttributeError: None object has no attribute 'set'`.
- Still not associate `results = tk.StringVar()` to `tk.Label(...`, see https://github.com/gman2682/school-project/issues/7
- Using a `tk.StringVar()` object in **not working** manner, see  [The Variable Classes (StringVar)](http://effbot.org/tkinterbook/variable.htm)
- Unintentionally assigning `None` to the left side variable.

---

You have at least to solve the FIRST one, to get your program running - even not working yet.
To get i working, you have to solve the SECOND on.

**Comment by gman2682** [comment]
How is it redefined when I have `result` and then I have `results`. Sorry I'm not quite understanding still..

**Comment by WK-GiHu** [comment]
@gman2682 

>How is it redefined when I have `result` and then I have `results`

You are right, my bad, the names are different, see my edited https://github.com/gman2682/school-project/issues/3#issuecomment-546248401

**Comment by gman2682** [comment]
Traceback (most recent call last):
  File "c:/Users/garri/Desktop/Final Project/PayrollCalculatorGUI.py", line 55, in <module>
    results = tk.Label(GUI, textvariable = "Total Pay: $" + "%.2f" % result).grid(row=3, column=1)
TypeError: must be real number, not StringVar

This is the error I am recieving.

**Comment by WK-GiHu** [comment]
@gman2682 

>This is the error I am recieving.

See, https://github.com/gman2682/school-project/issues/9

---

https://github.com/gman2682/school-project/blob/e945f0102a317b07aaa259fdbb140a69872524bb/PayrollCalculator.py#L53

The Line 53 has **5 Errors**:
- Still not associate `result = tk.StringVar()` to `tk.Label(...`, see https://github.com/gman2682/school-project/issues/7
- Using the parameter `textvariable` in **not working** manner,  read again [How to associate a Tkinter variable with a label.](http://effbot.org/tkinterbook/label.htm)
- Using a `tk.StringVar()` object in **not working** manner, see  [The Variable Classes (StringVar)](http://effbot.org/tkinterbook/variable.htm), this lead to `TypeError: must be real number, not StringVar`, see: https://github.com/gman2682/school-project/issues/9
- Try, to use a non existent value, see https://github.com/gman2682/school-project/issues/3#issuecomment-546453530
- Unintentionally assigning `None` to the left side variable.

**Comment by gman2682** [comment]
I've read all of these and still not quite getting what they do. I had the `results = tk.Label(GUI, textvariable = "Total Pay: $" + "%.2f" % result).grid(row=3, column=1)` like this when I had a salary variable in the start and it worked. How would I fix it?

**Comment by WK-GiHu** [comment]
@gman2682 

https://github.com/gman2682/school-project/blob/b8ea20e6ccbdce3bce9ce8addafaeb4a0ea997f4/PayrollCalculator.py#L30
### Great solution, i'm not noticed yet that you aware of using `OOP` coding style.

- [ ] It is working now
- [ ] Still not working, i get errors

---

>I've read all of these and still not quite getting what they do
>How would I fix it?

You have solved 4 of 5 errors, which did you not understand?

---

>I had the `results = tk.Label(GUI, textvariable = "Total Pay: $" + "%.2f" % result)...` like this when I had a `salary` variable in the start

Sorry, didn't get the second part of this sentence?

---

>and it worked

Yes, you didn't faced any error message as the left side variable is unused.
https://github.com/gman2682/school-project/blob/b8ea20e6ccbdce3bce9ce8addafaeb4a0ea997f4/PayrollCalculator.py#L55
The Line 53 has **1 Error**
- Unintentionally assigning `None` to the left side variable.
  **To solve this**:
  - [ ] Read: [tkinter-attributeerror-nonetype-object-has-no-attribute-attribute-name](https://stackoverflow.com/questions/1101750/tkinter-attributeerror-nonetype-object-has-no-attribute-attribute-name)**
