### ISSUE TITLE
tax = states_dict[i]

### ISSUE THREAD

**Issue by WK-GiHu** [gman2682/school-project#5]
@gman2682 

https://github.com/gman2682/school-project/blob/4841bf64757e5e9396e522afaab5fbe1e61bbdb1/PayrollCalculator.py#L18
- That's, **wrong**, enable this line 18, by removing the `#`, and see the error message.
- This throws a `Unknown: "i"` error.
- Where did you get `i` from?
- Why have you choosen to use `i` at all?

---

You have checked this https://github.com/gman2682/school-project/issues/1#issue-510505843, but it seems you didn't read or didn't get it?
   >- [x] Read [The Python Tutorial - 5.5. Dictionaries](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)

Read it again, follow the example how to get the Telephone number from `'jack'`.
Take the Tour at [Tutorialspoint - Python - Dictionary](https://www.tutorialspoint.com/python/python_dictionary.htm), there are also ***Live Demos***.

- [x] **Edit line 18 accordingly**.

---

- [x] To see, what you get, insert the following after line 18:
  **Note**: This will only work if the statment in line 18 can evaluated correct.
    ```
    print('tax in {} is {}'.format(state, tax))
    ```

**Comment by gman2682** [comment]
I can put in any state in the `states_dict['']` as like `states_dict['Alabama']` but I need it to run with every tax and not just one state. How would I approach that?

**Comment by gman2682** [comment]
Traceback (most recent call last):
  File "C:\Users\garri\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:/Users/garri/Desktop/Final Project/PayrollCalculatorGUI.py", line 29, in calculate
    result = result.set(salary)
UnboundLocalError: local variable 'result' referenced before assignment

Getting this error when try running and using the button

**Comment by WK-GiHu** [comment]
@gman2682 

You are close,
read: https://github.com/gman2682/school-project/issues/6#issue-511432963
continue with: https://github.com/gman2682/school-project/issues/3#issue-510874994
