### ISSUE TITLE
UnboundLocalError: local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by WK-GiHu** [gman2682/school-project#6]
@gman2682 

>result = result.set(salary)
>UnboundLocalError: local variable 'result' referenced before assignment
>
>Getting this error when try running and using the button

https://github.com/gman2682/school-project/blob/9dd34f61f41b3a6f39b1606b2338d2371595ccd2/PayrollCalculator.py#L29

The error message tells: you want to use ` = results` on the right side of ` = ` before you assign and define it to the left side to `results = ...`. That's not possible!

**You can't define a `variable` by using the `variable` itself!**
Disable it for now with `# `, then you should be able to see the console prints.

First you have to fullfil: associate a Tkinter variable with a label see: https://github.com/gman2682/school-project/issues/3#issue-510874994

**Comment by gman2682** [comment]
I try using `salary` or `result` from the defined function `calculate` but `salary` is already in the function and can't be used outside of it?

**Comment by WK-GiHu** [comment]
@gman2682 

>but `salary` is already in the function and can't be used outside of it?

See https://github.com/gman2682/school-project/issues/3#issuecomment-545616116
