### ISSUE TITLE
.set(salary)

### ISSUE THREAD

**Issue by WK-GiHu** [gman2682/school-project#8]
@gman2682 

>but salary still is undefined.

https://github.com/gman2682/school-project/blob/5244feca663ea7399c092232950d7fb969fa30ad/PayrollCalculator.py#L29
Add the following, after Line 29, to see, `salary` works:
```
print('tax in {} is {} result in salary:{}'.format(state, tax, salary))
```

---

https://github.com/gman2682/school-project/blob/5244feca663ea7399c092232950d7fb969fa30ad/PayrollCalculator.py#L54

The statement as shown in Line 54 is OK, but:
-  Why have you moved this statement and don't follow the **template** => https://github.com/gman2682/school-project/issues/2#issue-510506089
- Have you read and understand https://github.com/gman2682/school-project/issues/3#issuecomment-545616116

**Comment by gman2682** [comment]
I went back and followed the template. I don't quite understand #3 though..

**Comment by WK-GiHu** [comment]
@gman2682 

>I went back and followed the template.

You have renamed to `resultsShown`, which is not a optimal name but OK.

https://github.com/gman2682/school-project/blob/1827d27962d4bddb13ec8545dd75d2414e71523d/PayrollCalculator.py#L31

This will fail with: `AttributeError: 'Label' object has no attribute 'set'`

---

Read [The Variable Classes (StringVar)](http://effbot.org/tkinterbook/variable.htm)

**Comment by gman2682** [comment]
Okay, I tried updating everything from what you've sent me. Code is updated and ready for review.

**Comment by WK-GiHu** [comment]
@gman2682 

>Code is updated

https://github.com/gman2682/school-project/blob/6b7efe24ec6acc17f74eedbc5fe39d33a4f1ff58/PayrollCalculator.py#L11
You have renamed, the reference variable to `tk.StringVar()`, again, it is OK - **don't touch it anymore**!

---

https://github.com/gman2682/school-project/blob/6b7efe24ec6acc17f74eedbc5fe39d33a4f1ff58/PayrollCalculator.py#L31
This is a valid statement, it is Ok - **don't touch it anymore**!

---

We can close this Issue.

**Comment by gman2682** [comment]
Code is updated ready for review.
