### ISSUE TITLE
TypeError: must be real number, not StringVar

### ISSUE THREAD

**Issue by WK-GiHu** [gman2682/school-project#9]
@gman2682 

>`TypeError: must be real number, not StringVar`

https://github.com/gman2682/school-project/blob/e945f0102a317b07aaa259fdbb140a69872524bb/PayrollCalculator.py#L53

### `"Total Pay: $" + "%.2f" % result`
The `TypeError` message tells, you want to format the reference `result`, which is of type `tk.StringVar`, to a **real number**

- `"%.2f"` expect a **real number string** at the right side of `%`
- `result` is a reference to a object of type `tk.StringVar`

Conclusion: These types are not compatible and therefore invalid.

### See also: https://github.com/gman2682/school-project/issues/3#issuecomment-546728884

**Comment by gman2682** [comment]
How do I make it so if someone presses calculate on 'choose a state' that it says "Invalid Input" or something?

**Comment by gman2682** [comment]
Code is updated for review

**Comment by WK-GiHu** [comment]
@gman2682 

You have doped to use `"Total Pay: $" + "%.2f" % result`, we can close this Issue.
